repos:
  - repo: https://github.com/pre-commit/pre-commit-hooks
    rev: v2.4.0
    hooks:
      # Simply check whether the files parse as valid python
      - id: check-ast
      # Prevent giant files from being committed
      - id: check-added-large-files
      # Detects the presence of private keys
      - id: detect-private-key    
      # Checks a common error of defining a docstring after code
      - id: check-docstring-first
  - repo: https://gitlab.com/pycqa/flake8
    rev: 3.9.0
    hooks: 
      - id: flake8
  - repo: https://github.com/pre-commit/mirrors-mypy
    rev: v0.812
    hooks:
      - id: mypy    

