repos:
    - repo: https://github.com/pre-commit/pre-commit-hooks
        rev: v2.4.0
        hooks:
        # Prevent giant files from being committed
        - id: check-added-large-files
        # Detects the presence of private keys
        - id: detect-private-key
        # Simply check whether the files parse as valid python
        - id: check-ast    
        # Ensures that a file is either empty, or ends with one newline
        - id: end-of-file-fixer
        # Checks a common error of defining a docstring after code
        - id: check-docstring-first

    - repo: https://gitlab.com/pycqa/flake8
        rev: v3.9.0
        hooks: 
        - id: flake8