repos:
-   repo: https://github.com/DimaKarpukhin/commit-msg-hook.git
    rev: aa73c9b58dad543e0bfee5df8f8bf1f92f041b2f
    hooks:
    -   id: commit-msg-hook
        args: [.git/COMMIT_EDITMSG]
        stages: [commit-msg]
-   repo: https://github.com/pre-commit/pre-commit-hooks
    rev: v3.4.0
    hooks:
        # Prevent giant files from being committed
    -   id: check-added-large-files
        stages: [push]
        # Detects the presence of private keys
    -   id: detect-private-key
        stages: [push]
        # Simply check whether the files parse as valid python
    -   id: check-ast
        stages: [push]
        # Checks yaml files for parseable syntax
    -   id: check-yaml
        stages: [push]
        # Trims trailing whitespaces
    -   id: trailing-whitespace
        stages: [push]
-   repo: https://github.com/asottile/reorder_python_imports
    rev: v2.4.0
    hooks:
    -   id: reorder-python-imports
        args: [--application-directories, '.:src', --py36-plus]
        stages: [push]
-   repo: https://github.com/pre-commit/mirrors-mypy
    rev: v0.812
    hooks:
    -   id: mypy
        stages: [push]
-   repo: https://gitlab.com/pycqa/flake8
    rev: 3.9.1
    hooks:
    -   id: flake8
        additional_dependencies: [flake8-docstrings]
        stages: [push]



